import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins, Special_Gothic_Expanded_One, } from "next/font/google";
import "./globals.css";
import IndexLayout from "@/components/layout/indexLayout";
import { Inter } from "next/font/google";



const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const specialGothicExpandedOne = Special_Gothic_Expanded_One({
  variable: "--font-special-gothic-expanded-one",
  subsets: ["latin"],
  weight: ["400",],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${specialGothicExpandedOne.variable} ${poppins.variable} relative antialiased`}
      >
        <IndexLayout>{children}</IndexLayout>
      </body>
    </html>
  );
}
